# Generated by Django 5.0.2 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='dueno_id',
            field=models.IntegerField(help_text='ID del cliente (User) dueño desde usuario_service. Se almacena como entero para mantener microservicios desacoplados.'),
        ),
    ]
