# Generated by Django 5.0.2 on 2026-01-04 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.servicio'),
        ),
    ]
