# Generated by Django 5.0.2 on 2026-02-06 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPeluquero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peluquero_id', models.IntegerField(help_text='ID del peluquero (User) desde usuario_service')),
                ('tipo', models.CharField(choices=[('NUEVA_CITA', 'Nueva Cita'), ('CITA_CONFIRMADA', 'Cita Confirmada'), ('CITA_CANCELADA', 'Cita Cancelada'), ('CITA_REPROGRAMADA', 'Cita Reprogramada'), ('RECORDATORIO', 'Recordatorio de Cita')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Notificación Peluquero',
                'verbose_name_plural': 'Notificaciones Peluqueros',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['peluquero_id', '-creada_en'], name='citas_notif_peluque_72bb8f_idx'), models.Index(fields=['peluquero_id', 'leida'], name='citas_notif_peluque_d7c137_idx')],
            },
        ),
    ]
