# Generated by Django 5.2.7 on 2025-10-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMascota', models.CharField(choices=[('PEQUEÑO', 'Pequeño'), ('MEDIANO', 'Mediano'), ('GRANDE', 'Grande')], max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_id', models.IntegerField()),
                ('peluquero_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('CANCELADA', 'Cancelada'), ('TERMINADA', 'Terminada')], default='REGISTRADA', max_length=20)),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.tarifa')),
            ],
        ),
    ]
