# Generated by Django 5.0.2 on 2026-01-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del servicio (puede ser URL de nube como Google Drive, Cloudinary, etc.)', null=True),
        ),
    ]
