# Generated by Django 5.2.7 on 2026-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_servicio_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE', max_length=20),
        ),
    ]
